name: run activitypub-testing test suite

on:
  push:
  workflow_dispatch:

jobs:
  test-actor:
    name: "`activitypub-testing test actor` node=${{ matrix.node-version }}"
    strategy:
      matrix:
        node-version: ['20.x', '21.x']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: ./bin/activitypub-testing
  
  tap-summary:
    name: "render a summary of TAP test report node=${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install deps and prepare npm package
        run: |
          npm ci
      - name: activitypub-testing -> tap/activitypub-testing.tap
        run: |
          mkdir -p tmp
          bin/activitypub-testing \
          | bin/assertion-ndjson-to-tap.js \
          | tee tmp/activitypub-testing.tap \
          | npx tap -R markdown - \
          | tee tmp/activitypub-testing.tap.md
      - name: save testing summary to GITHUB_STEP_SUMMARY
        run: |
          cat tmp/activitypub-testing.tap.md >> $GITHUB_STEP_SUMMARY

  # this is possible, and the proof is included, but it's not recommended.
  # It's nicer to maintain the shell script in a standalone file,
  # because then you can run the script in contexts other than github actions
  # (e.g. to test it locally, or to use with tools like shellcheck).
  # note: there may be other ways to do this, but this one works with nektos/act despite https://github.com/nektos/act/issues/2287
  test-actor-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci
    - name: run and test server
      run: |
        debug() {
          >&2 echo
          >&2 echo "$@"
        }
        main() {
          debug "starting server"
          npm start &
          serverPid=$?
          serverUrl=http://localhost:8000

          debug "waiting for server to be available at $serverUrl"
          until curl --output /dev/null --silent --head --fail $serverUrl; do
            >&2 printf '.'
            sleep 5
          done
          debug "server is available at $serverUrl"

          me="$serverUrl/users/me"
          debug "running activityput-testing test actor $me"
          npx activitypub-testing test actor $me
        }
        main
